### ISSUE TITLE
1.0.0-alpha vs. 1.0.0-alpha.1

### ISSUE THREAD

**Issue by zero-24** [coolcat-creations/plg_fields_owlimg#5]
The update server should not point to a different version than the last one. ;)

https://github.com/coolcat-creations/plg_fields_owlimg/blob/master/manifest.xml#L9

https://github.com/coolcat-creations/plg_fields_owlimg/blob/master/owlimg/owlimg.xml#L10

**Comment by coolcat-creations** [comment]
Thanks, corrected the xml
