### ISSUE TITLE
This field shows on Category blog view

### ISSUE THREAD

**Issue by Bodge-IT** [coolcat-creations/plg_fields_owlimg#8]
I didn't even know field data was available in that view.
Any ideas how to fix, probably a simple override?

It's delivered through the $this->item->event->afterDisplayContent;

I've commented that line for now.

**Comment by coolcat-creations** [comment]
Sorry I did not respond I somehow missed track of it. you can disable automatic display an call your field through an override.

**Comment by Bodge-IT** [comment]
lol, I've forgotten what I was working on!  Think I figured it out though but thanks for the update.
